main: whomas.randomtp.plugin.TeleportMe
name: TeleportMe
version: 1.8.0.1
api-version: 1.16
author: BigWhomas
description: A random teleportation plugin.
commands:
   tpme:
      description: Allows the player to randomly teleport
      usage: /<command>
   home:
      description: test
      usage: /<command>
   warp:
      description: Allows player to warp to public warps
      usage: /<command>



   